"use client";
import { useMemo, useState } from "react";
import { Business, Product } from "@/lib/types";
type CartItem = Product & { quantity: number };
export function WhatsAppCart({ business, products }: { business: Business; products: Product[] }) {
 const [cart,setCart]=useState<CartItem[]>([]); const [name,setName]=useState(""); const [address,setAddress]=useState(""); const [note,setNote]=useState("");
 const total=useMemo(()=>cart.reduce((s,i)=>s+i.price*i.quantity,0),[cart]);
 const add=(p:Product)=>setCart((items)=>{const ex=items.find((i)=>i.id===p.id); return ex?items.map((i)=>i.id===p.id?{...i,quantity:i.quantity+1}:i):[...items,{...p,quantity:1}];});
 const change=(id:string,delta:number)=>setCart((items)=>items.map((i)=>i.id===id?{...i,quantity:Math.max(0,i.quantity+delta)}:i).filter((i)=>i.quantity>0));
 const href=useMemo(()=>{const lines=[`Pedido para ${business.name}`,"",...cart.map((i)=>`- ${i.quantity} x ${i.name}: RD$${(i.price*i.quantity).toFixed(2)}`),"",`Total: RD$${total.toFixed(2)}`,`Cliente: ${name || "Pendiente"}`,`Entrega/retiro: ${address || "Pendiente"}`,`Nota: ${note || "N/A"}`]; return `https://wa.me/${business.whatsapp.replace(/\D/g,"")}?text=${encodeURIComponent(lines.join("\n"))}`},[business,cart,total,name,address,note]);
 const cats=Array.from(new Set(products.map((p)=>p.category?.name ?? "Menú")));
 return <div className="grid gap-8 lg:grid-cols-[1fr_360px]"><section className="space-y-8">{cats.map((cat)=><div key={cat}><h2 className="mb-4 text-2xl font-black">{cat}</h2><div className="grid gap-4 sm:grid-cols-2">{products.filter((p)=>(p.category?.name??"Menú")===cat).map((p)=><article key={p.id} className="card"><div className="mb-4 flex h-36 items-center justify-center rounded-2xl bg-gradient-to-br from-emerald-50 to-orange-50 text-5xl">🍽️</div><h3 className="text-lg font-black">{p.name}</h3><p className="mt-1 min-h-10 text-sm text-slate-600">{p.description}</p><div className="mt-4 flex items-center justify-between"><strong>RD${p.price.toFixed(2)}</strong><button className="btn-primary !py-2" onClick={()=>add(p)}>Agregar</button></div></article>)}</div></div>)}</section><aside className="card h-fit lg:sticky lg:top-24"><h2 className="text-2xl font-black">Carrito</h2><div className="mt-4 space-y-3">{cart.length===0?<p className="text-sm text-slate-500">Agrega productos para iniciar el pedido.</p>:cart.map((i)=><div className="flex items-center justify-between" key={i.id}><span className="text-sm">{i.quantity} x {i.name}</span><div className="flex gap-2"><button onClick={()=>change(i.id,-1)} className="rounded-lg border px-2">-</button><button onClick={()=>change(i.id,1)} className="rounded-lg border px-2">+</button></div></div>)}</div><div className="my-4 border-t pt-4 text-xl font-black">Total RD${total.toFixed(2)}</div><div className="space-y-3"><input className="input" placeholder="Nombre del cliente" value={name} onChange={(e)=>setName(e.target.value)} /><input className="input" placeholder="Dirección o indicar retiro" value={address} onChange={(e)=>setAddress(e.target.value)} /><textarea className="input" placeholder="Nota adicional" value={note} onChange={(e)=>setNote(e.target.value)} /></div><a className="btn-primary mt-4 w-full" href={href} target="_blank" rel="noreferrer">Pedir por WhatsApp</a></aside></div>;
}
